### ISSUE TITLE
'Disabled' text, 'div' as button with it instead of disabled button

### ISSUE THREAD

**Issue by apximax** [doskachok/magellan#70]
The suggestion is to remove 'disabled' state from the Text component. At least it doesn't follow standard html way of determining what stuff could be disabled.
If we need we can create another Text component that inherits and extends our standard one. We can have eg PrimaryText, SecondaryText, HintText, or even (nope, don't do this..) SmallText, but not <Text disabled={true}>

This is used when we have button looks like just text line and arrow. Without a button-looking wrapper around.
So let it be button exactly. Some new one button like ButtonBlabla that extends the standard one, or <Button fill={false}>

**Comment by doskachok** [comment]
Solved in: #71
